---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_facts:
      cloud: ospcloud
      region_name: RegionOne
    register: result

  - name: Delete instances along with floating ip
    os_server:
      cloud: ospcloud
      name: "{{ item.name }}"
      state: absent
      delete_fip: true
    with_items: "{{result.ansible_facts.openstack_servers}}"
