---
# tasks file for base-config. yum clean cannot be used with yum module as per ansible documentation
  - name: Run yum clean
    shell: yum clean all

  - name: Install EPEL repos 
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present 

  - name: Install pip
    yum:
      name:
        - python-pip
        - gcc
      state: latest
